CREATE TABLE IF NOT EXISTS note (
id IDENTITY NOT NULL PRIMARY KEY,
title VARCHAR(256) NOT NULL,
content CLOB NOT NULL
);

CREATE TABLE users(
	username VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
	password VARCHAR_IGNORECASE(500) NOT NULL,
	role ENUM('USER', 'ADMIN') NOT NULL,
	enabled BOOLEAN NOT NULL
);