CREATE TABLE users(
username VARCHAR(50) PRIMARY KEY NOT NULL,
password VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
id IDENTITY NOT NULL PRIMARY KEY,
user_id VARCHAR(50) NOT NULL,
title VARCHAR(256) NOT NULL,
content CLOB NOT NULL
);